[input]
base_directory = "/Users/matthewkudija/code/cca-blog/output"
html_selector = "main"

[[input.files]]
path = "on-the-enduring-importance-of-humble-virtue.html"
url = "/on-the-enduring-importance-of-humble-virtue.html"
title = "On the Enduring Importance of Humble Virtue"

[[input.files]]
path = "new-year-old-truths-an-invitation-from-columbus-classical-academy.html"
url = "/new-year-old-truths-an-invitation-from-columbus-classical-academy.html"
title = "New Year, Old Truths: An Invitation from Columbus Classical Academy"

[[input.files]]
path = "on-the-importance-of-struggle-in-a-good-education.html"
url = "/on-the-importance-of-struggle-in-a-good-education.html"
title = "On the Importance of Struggle in a Good Education"

[[input.files]]
path = "on-holding-sudents-emotions-accountable-to-the-truth.html"
url = "/on-holding-sudents-emotions-accountable-to-the-truth.html"
title = "On Holding Sudents’ Emotions Accountable to the Truth"

[[input.files]]
path = "on-the-humble-pursuit-of-true-beauty.html"
url = "/on-the-humble-pursuit-of-true-beauty.html"
title = "On the Humble Pursuit of True Beauty"

[[input.files]]
path = "on-what-makes-a-school-excellent.html"
url = "/on-what-makes-a-school-excellent.html"
title = "On What Makes a School Excellent"

[[input.files]]
path = "were-in-contract.html"
url = "/were-in-contract.html"
title = "We're In Contract!"

[[input.files]]
path = "applications-now-open.html"
url = "/applications-now-open.html"
title = "Applications Now Open!"

[[input.files]]
path = "cca-announces-our-academic-dean.html"
url = "/cca-announces-our-academic-dean.html"
title = "CCA Announces Our Academic Dean"

[[input.files]]
path = "welcome.html"
url = "/welcome.html"
title = "Welcome!"

[[input.files]]
path = "cca-announces-our-headmaster.html"
url = "/cca-announces-our-headmaster.html"
title = "CCA Announces Our Headmaster"